image:
  file: .gitpod.dockerfile

# List the start up tasks. Learn more: https://www.gitpod.io/docs/configure/workspaces/tasks
tasks:
  - name: Script Task
    init: echo 'init script' # runs during prebuild => https://www.gitpod.io/docs/configure/projects/prebuilds
    command: echo 'start script'


ports:
  - port: 8080
    onOpen: open-preview
  - port: 9000-9999
    onOpen: ignore





# Learn more from ready-to-use templates: https://www.gitpod.io/docs/introduction/getting-started/quickstart
